// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"database/sql"
	"github.com/go-playground/validator/v10"
	"latihan_sqlc/interface/api/controller"
	"latihan_sqlc/internal/repositories"
	"latihan_sqlc/internal/service"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, validate *validator.Validate, db *sql.DB) *controller.BookControllerImpl {
	bookRepositoriesImpl := repositories.NewBookRepositoriesImpl(ctx, db)
	bookServiceImpl := service.NewBookServiceImpl(bookRepositoriesImpl, validate)
	bookControllerImpl := controller.NewBookControllerImpl(bookServiceImpl)
	return bookControllerImpl
}
