version: '3.1'

services:
  books_db:
    image: mysql:latest
    container_name: book_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - '3307:3306'
    volumes:
      - ./internal/mysql/books.sql:/docker-entrypoint-initdb.d/books.sql
