// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	ID     int32
	Title  string
	Author string
}

type Customer struct {
	IDCustomer    int32
	NameCustomer  string
	EmailCustomer sql.NullString
}

type SchemaMigration struct {
	Version string
}
